CREATE TABLE Employees (
    employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100),
    role VARCHAR2(50),
    hire_date DATE DEFAULT SYSDATE
);


CREATE TABLE Products (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR2(100) NOT NULL,
    price NUMBER(10,2) NOT NULL,
    stock_quantity NUMBER DEFAULT 0
);


CREATE TABLE Customers (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100),
    phone VARCHAR2(20)
);


CREATE TABLE Sales (
    sale_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER NOT NULL,
    employee_id NUMBER NOT NULL,
    customer_id NUMBER,
    quantity NUMBER NOT NULL,
    sale_date DATE DEFAULT SYSDATE,
    total_amount NUMBER(10,2) NOT NULL,

    CONSTRAINT fk_sales_product 
    FOREIGN KEY (product_id) REFERENCES Products(product_id),

    CONSTRAINT fk_sales_employee 
    FOREIGN KEY (employee_id) REFERENCES Employees(employee_id),

    CONSTRAINT fk_sales_customer 
    FOREIGN KEY (customer_id) REFERENCES Customers(customer_id)
);


CREATE TABLE Holidays (
    holiday_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    holiday_date DATE NOT NULL UNIQUE,
    holiday_name VARCHAR2(100) NOT NULL
);


CREATE TABLE Audit_Log (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_type VARCHAR2(50) NOT NULL,
    table_name VARCHAR2(50) NOT NULL,
    action_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_name VARCHAR2(50),
    details VARCHAR2(4000)
);